# vim: ts=2:sts=2:sw=2:expandtab:smarttab:

pipeline:
  build:
    image: golang
    commands:
      - go build -o bin/server cmd/server/main.go

  publish-docker:
    image: plugins/docker
    repo: ontrif/flux
    tag:
      - latest
      - ${DRONE_TAG}
    when:
      event: tag
    secrets: [ docker_username, docker_password ]
